title: <p align="center"> Pradeep Kumar </p>
logo: /assets/img/pradeep.jpg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
   <a href="https://github.com/pkumarljmu">GitHub</a>
  
  <br>   
  I'm working on Cloud Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Also handing the Big Data from real-time data achieved from Realtime Systems.
  Worked with Apple Research at Big Data Analytics team.
  Working with British Telecom as Data Engineering Architect since 3 years.
  <br>
  </p>



theme: jekyll-theme-minimal
